FROM registry.cn-hangzhou.aliyuncs.com/zhangbo007/node:14.18.0-alpine
#FROM alpine
# 设置镜像作者
LABEL MAINTAINER="zhangbo"

# 设置工作目录
WORKDIR /app

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser


# 设置国内阿里云镜像站、安装chromium 102、文泉驿免费中文字体等依赖库
#RUN echo "https://mirrors.aliyun.com/alpine/v3.11/main/" > /etc/apk/repositories \
#    && echo "https://mirrors.aliyun.com/alpine/v3.11/community/" >> /etc/apk/repositories \
#    && echo "https://mirrors.aliyun.com/alpine/edge/testing/" >> /etc/apk/repositories \
#    && apk -U --no-cache update && apk -U --no-cache --allow-untrusted add \
#      zlib-dev \
#      xorg-server \
#      dbus \
#      ttf-freefont \
#        nss \
#        freetype \
#        freetype-dev \
#        harfbuzz \
#        ca-certificates \
#      chromium \
#      wqy-zenhei@edge \
#      bash \
#      bash-doc \
#      bash-completion -f



#RUN echo @edge http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && apk add


# Installs latest Chromium (100) package.
#RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories




RUN echo "https://mirrors.aliyun.com/alpine/v3.11/main/" > /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/v3.11/community/" >> /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/latest-stable/testing" >> /etc/apk/repositories \
 && apk --no-cache  update && apk add --no-cache --force-broken-world --allow-untrusted add  \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn \
      zlib-dev \
 wqy-zenhei@edge \
      bash \
      bash-doc \
      bash-completion \
      font-adobe-100dpi \
      ttf-dejavu \
      fontconfig
